import json

with open('json.txt', encoding='utf-8') as f:
    j = f.read()


data = json.loads(j)

rows = data['table']['rows']

name_set = set()
package_set = set()

print('=' * 30)

for row in rows:
    result = row[1][0]
    name = result['name']
    url = result['url']
    package = url.split('/')[4]

    name_set.add(name)
    package_set.add(package)
    print(name,';',package)


loan_app_name_set = {
    'CashToGo',
    'PNB Loans',
    'PondoPeso',
    'Easy Peso',
    'Fast Loan',
    'Qcash',
    'Cashalo',
    'CashLending',
    'LoanChamp',
    'Pesoloan',
    'Creditpeso',
    'Cashwagon',
    'cashme',
    'CashMart',
    'GCash',
    'First Peso',
    'Fast Cash',
    'SwakCash',
    'LalaPeso',
    'GoPeso',
    'Peso Expert',
    'Cashcash Philippines',
    'Flash Cashloan',
    'Good Loan',
    'Cashup',
    'QuickCash',
    'Credit Loan',
    'Big cash',
    'cash-money-loan',
    'Pesos.ph',
    'Coopa Loans',
    'Kwik Cash',
    'HappyPeso',
    'Lemon loan',
    'Super Cash',
    'Simple Loan',
    'Fast Cash Loan',
    'U-peso',
    'LoanIt',
    'Super Cash-PH',
    'Peso Tree',
    'Peso Advance',
    'Peso2Go',
    'CashVan',
    'Cashmoto',
    'PesoQ',
    'RoboCash',
    'Rainbow Cash',
    'Q Money - Mobile loans',
    'WowCash',
    'Pondo Loan',
    'CashWhale',
    'Hi peso',
    'MF-cash',
    'Peso Cash',
    'MeLoan',
    'LendingCash',
    'Easy Loans',
    'Fast Cash Loans',
    'Doggy Loan',
    'Cash Peso',
    'Math Cash',
    'Pata cash',
    'Giant Cash',
    'GetPeso',
    'Pesolaso',
    'Premier Loans',
    'Lending Cash',
    'Peso Salamat',
    'Fowl Loan',
    'Dragon Loan',
    'Chook Cash',
    'Cash Frenzy Casino',
    'Loans',
    'Flash Cash',
    'CashPeso',
    'Free Bitcoin Cash',
    'QuickPeso',
    'M Loans',
    'MegaLoan',
    'CashX',
    'PNB Loan',
    'cashloan',
    'Fast Cashloan',
    'Loan Calculator IQ',
    'Mcash',
    'Grow Loans',
    'MFPeso',
    'bambuloan',
    'Free Money Cash - Earn Money and Get Paid',
    'Squirrel Loan',
    'Emergency Loans',
    'Loan Money USA',
    'Fanaka Pesa Loans',
    'Azima Loans',
    'Tala cash loan',
    'Easy Loan',
    'Quick Loan Credit',
    'Mkopo loans',
    'Golden-Life Loans',
    'Mobile Cash Loans',
    'Your payday loans online personal',
    'Instant Loans',
    'Diamond Trust Loans',
    'Swit Loan',
    'Cash Express',
    'gCash-Make Money',
    'Stawisha Loans',
    'Peso Cash Loan',
    'Fast Loan 7Y',
    'mKash Loans',
    'Bad Credit Loans',
    'PesoLoco',
    'MangoCash',
    'Consultar Personal Loan and Fast Mini Loans Calculator',
    'Pinoy Peso',
    'UKash - Personal Loans',
    'Shark loan',
    'Online Peso',
    'OCash Loans',
    'Simple Loans',
    'Quick Peso',
    'CashKart',
    'Pesoplus',
    'Peso Peso',
    'MFcash',
    'cash loan',
    'Tal akash loan',
    'Loan & Interest Calculator',
    'ITALA Loan',
    'Legit Loan',
    'LOANS - Instant FULIZA Loans to Mpesa',
    'Spin to Win Earn Money : Cash Rewards',
    'Upeso',
    'Tala Haraka Loans',
    'Fast Loans Online',
    'MkopaLoans',
    'Cash Advance',
    'Loan Globally',
    'Nawiri Loans',
    'QASH LOANS',
    'BigCash',
    'Easy Cash Loans',
    'UpesoLending',
    'cash-money',
    'XCash',
    'LoanSmart',
    'Loan For Unemployed - Everything You Need to Know',
    'Quick Emergency Loans',
    'CRB Loan Status Checker',
    'Mfadhili Loans',
    'Student Loan',
    'Wasafi Loans',
    'Halisi Loans',
    'Fast Mobile Loans',
    'Safi Loans',
    'Daima Chapchap Loans',
    '1Finance Loan',
    'Easy Cash',
    'M-kop Loans',
    'Lucky Cash',
    'Quick Cash',
    'Flourish Loans',
    'Cash Umbrella',
    ' Cash Keyboard',
    'Online Loans',
    'HandCash',
    'Cash wallet',
    'Cash US',
    'Fast Peso',
    'Fintech Cash Loans',
    'Loans Shwari',
    'Jiinue Loans',
    'Free Paypal Cash - Get Free Coins and Rewards',
    'Advance Money - Small Loan',
    'Loan 24',
    'Loan Calculator',
    'CredoApp Salary Loans',
    'U Peso',
    'CashApp',
    'Loans - Instant Loans to Mpesa',
    'Fast cash lending',
    'Loans!',
    'Tala Xpress Loans',
    'Pewa Loans',
    'Lucky Cash Casino',
    'Student Loans',
    'VidCash- Watch Video & Earn Money',
    'Borrow money loan guide! payday loans credit score',
    'Tala Loans - Mkopo Poa',
    'Umoja loans',
    'Comfy Loan',
    'LoanFree',
    'QuickCash123',
    'Casha',
    'Cashman Casino',
    'MCo-opCash',
    'Loan Shark',
    'CASH LOAN 2 MINUTES',
    'Quick M - loans',
    'Payday advance - Payday loans guide early paycheck',
    'Easy Direct Loans',
    'Eazy Loans',
    'Quick Loan',
    'EasyLoanWala',
    'JOY Cash',
    'Jubilee Loans Instant Cash',
    'Inuka Quick Loans',
    'Hi Cash',
    'Tunza Loans',
    'Ziada Loans',
    'Mobi loans',
    'Msingi Loan',
    'HappyCash',
    'soCash',
    'Business Loan',
    'ePesa Loans',
    'SuperCash',
    'Rapid Loans',
    'CashHappy',
    'GetGo Peso+',
    'Make Money Online Earn Free Cash App',
    'Fast Money & Pay Day Loan',
    'Tala M-Cash - Instant Loans To Mpesa',
    'Online Loan',
    'Credit Cash',
    'My Tala Loans kenya Mpesa',
    'Mabilis Cash',
    'Afinoz',
    'ASAP Loan Finder(Find Personal and Business loans)',
    'Balikbayad',
    'OFW and Seaman',
    'Loans',
    'Apply',
    'For',
    'Online',
    'Loan',
    'Cashope',
    'CashMaya',
    'Payday',
    'Advance',
    'Loan',
    'Online',
    'LoanMart | Get',
    'Cash',
    'FAST',
    'loans.com.au',
    'Smart',
    'Money',
    'Cashloan',
    'Market',
    'Mobile',
    'Loan',
    'Cash',
    'Creditpeso - borrow & get',
    'Peso!',
    'BADEVCO',
    'QUICKCASH',
    'Cash',
    'Cat',
    'Cash',
    'Loan',
    'Market',
    'Cashafin',
    'CashFlyer',
    'Express',
    'Loans.Get',
    'Money',
    'Online.Go',
    'Easy',
    'Loan',
    'Gogo',
    'cash',
    'GrantPeso',
    'Guide',
    'for Mudra Loan 2019',
    'Guide for Tala loan Philippines for fast cash',
    'Guide for Tala Loans Kenya - Personal loans',
    'Hi Cash Pro',
    'IDFC FIRST Loans',
    'iGo Insta Personal loan',
    'Instant Loan App Online',
    'Instant Personal Loan App',
    'InstaPeso',
    'Leeway Loan',
    'Loan Cash USA',
    'Loan For Unemployed',
    'Loan Market',
    'Merch Loan',
    'Mkopo Haraka (Easy and Cheap Loans)',
    'My Capital Loan',
    'Payday loan comparison',
    'PeraPocket',
    'PesoGo',
    'Pocket Loan',
    'Softcash',
    'StashFin',
    'Tumiwa Loan',

}

loan_app_set = {
    'com.loan.cashtogo',
    'com.app.mkopopnb',
    'ph.pondopeso.mnl.jk',
    'com.globe.gcash.android',
    'com.unipeso.swakcash',
    'com.pesoloan',
    'com.flashcashloan.app',
    'com.oriente.cashalo',
    'ph.cashwagon.mobile.android',
    'com.yipai.mvparms.lalapeso',
    'com.unipeso.variant',
    'com.lanhai.upesocash',
    'com.easy.cash.loan',
    'com.app.easyloan',
    'ph.fk.mycash',
    'com.unipeso.phone',
    'xm.jinyu.mantang',
    'id.expert.peso',
    'com.cashwhale.loan',
    'ph.robocash.mobile',
    'com.credit.cash.loan',
    'ph.corp.hipeso.wireless',
    'ph.tq007.pocket',
    'com.firstpeso.app',
    'com.qzjf.supercash_p.ph',
    'ph.cashwagon.mobile',
    'ph.fk.cmuedi',
    'com.ushengsheng.fcash',
    'com.pesoadvance.app',
    'com.wdjk.mcvay',
    'yx.chushen.ruhua',
    'com.onespotapps.quickcash',
    'com.bq73.pocket',
    'com.xianjindai.cashloanbackground',
    'ph.hupan.loan',
    'com.crazy.loan',
    'com.xmhaibao.fcash',
    'com.moda.loan',
    'cn.taqu.fcash',
    'com.philtechie.mathcash',
    'com.mini.loan',
    'com.udhaarkart.alan.gppeso',
    'ph.fk.pondoloan',
    'ph.cashme.loana',
    'com.peso2go',
    'com.giant.cash.three',
    'com.lendingcash.loan',
    'cg.fanrong.changsheng',
    'com.ps.getpesoa',
    'com.pesolaso.pesolaso.tech',
    'com.pesocredit.finlabtech',
    'gregdev.org.biasharaloans',
    'ph.lending.cash',
    'loanchamp.com.loanchamp',
    'com.firestorm.sea.loanmarket',
    'ph.floan.payloan',
    'com.php.tools',
    'ph.money.pocket',
    'com.djkuwl.chookc',
    'slots.pcg.casino.games.free.android',
    'com.flashcash.app',
    'com.cashwhale.appv1',
    'com.cash.loan.online',
    'com.go.study.pe',
    'ph.cmoney.cashpeso',
    'crypto.aliens.bch',
    'com.unipeso.megaloan',
    'cashx.apps.vergefinance.com.cashx',
    'com.peso.salamat.flbxjd',
    'com.cashwhale.app',
    'ph.fcash.payloan',
    'com.tmart.pesoq',
    'com.psw.mymc',
    'cn.mango',
    'ph.cashme.loanb',
    'cash.fast.easyloans',
    'pesosph.ph',
    'oklik.flb.jkcash.com',
    'brendanyabu.com.fanakaloans',
    'com.cashvan.alan.cashvan',
    'ph.fastcash.payloan',
    'ph.switloan.cash',
    'com.mmfqphl.cashexpress',
    'eu.gcashapp',
    'com.lemon.loan',
    'com.unit.togo',
    'com.fastcashloan.appv1',
    'com.pesotree.app',
    'com.whale.appv2',
    'com.yipai.mvparms.cashkart',
    'com.app.loanit',
    'ph.pesoplus.loans',
    'com.yinshan.happypeso',
    'cn.busoas',
    'com.kmrlla.fowll',
    'oklik.flb.jkcash.com.betaApk4',
    'com.creditloan.phicash',
    'ca.sh.fast.mloans',
    'com.loans.mpesafuliza',
    'com.finacleGlobal.pataCash',
    'com.mpesaquickloans.easyloans',
    'com.businessloans.instant',
    'myloans.philippines',
    'com.simple.nng',
    'pilomange.spin.winearnmoney',
    'tg.zhuoer.buqun',
    'cn.mgchwe',
    'com.fast.p.cashloans',
    'ph.cashmoto.m.loan',
    'com.finance.credit.quickcredit',
    'com.alan.phil.to',
    'ph.jan.cash',
    'com.bajueluk.dragonl',
    'com.cl.hc',
    'com.phil.det.tech',
    'com.mfadhili.com',
    'com.okoa.tala.halisiloans',
    'com.app.mobiloan',
    'com.safi.ed',
    'gregdev.org.nawiri',
    'com.daimachapchap.com',
    'ph.peso.cash',
    'com.crbstatuus.apps.loanscheck',
    'com.musk.loantalacash',
    'com.shark.loan',
    'com.etyuias.dogyl',
    'com.ebrun.cashwallet',
    'com.cashnow.forus',
    'ph.fk.cmcashloan',
    'ph.hello.filipino',
    'com.vergefinance.apps.cashx',
    'com.vcbuiol.squl',
    'onchoke.org.jiinue',
    'com.loan.okoa.shwari',
    'com.yipai.mvparms.cashloan',
    'ph.pesoLoco',
    'ph.fast.peso',
    'com.india.loans.cash',
    'com.go.alan.ph',
    'com.burenkov.yplcrd',
    'com.tloan.sigmacodema.talakashloan',
    'com.wdjk.mcash',
    'id.co.quick.peso',
    'money.cashadvance.payday.loans.calculator',
    'com.dansyosoftwares.tala.umojaloans',
    'inc.qash.quick',
    'com.eonsoft.LoanCalc',
    'com.kart.alan.peso',
    'com.cashwhale.cashapp',
    'com.financetech.instantloanstompesa',
    'com.wdjk.mc',
    'com.samri.loans.apps.in.kenya.to.mpesa.instantloans',
    'com.quickcash123',
    'com.lifelinefinance.kwikcashloans',
    'com.joypie.easyloan.ph',
    'com.opened.safe',
    'com.unipeso.xcash',
    'com.coco01.sharkloan',
    'cn.mymano',
    'com.faulu.online.kenya',
    'com.luckysky.ucashph',
    'com.haraka.loansapptalafinance',
    'com.fast.p.easycash',
    'bestnew.mangocash.com',
    'com.afinoz',
    'com.app.creditors',
    'com.balikbayad',
    'com.bsol.onlineloan',
    'com.cashope.appv1',
    'com.haiwaijiekuan.ppd.android',
    'com.kianairline.paydayloans',
    'com.loanmart.mobile',
    'com.loans.smartmoney',
    'com.mabo.cashloan.market',
    'com.mobilecash.loan',
    'com.php.tools',
    'ph.com.badevco.app',
    'com.xiaozhoudao.magic_cash',
    'com.mabo.cashloan.market',
    'com.cashafin.appv1',
    'ph.flyer.loan',
    'ru.loans.express',
    'com.app.LoanBazaar',
    'com.fl.gogocash',
    'cn.phpgranteso',
    'com.mudra.loan.yojna.guide2019',
    'mkopotaliaapps.talaloanapp',
    'com.digitalken.jeff.talakamoan',
    'com.hi.cash.pro',
    'com.capitalfirst',
    'com.iifl.igo',
    'com.batkiew.instantloan',
    'com.gopaysense.android.boost',
    'com.lanyou.web.instapreso',
    'com.app_leewayloan900.layout',
    'tsc.loancashusa.com',
    'com.proyectoultra83',
    'com.jrweid.pilipinas.loanmarket',
    'tsc.merchloan.com',
    'loan.com.mkopo.haraka.loans',
    'tsc.mycapitalloan.com',
    'com.tiim.cred24',
    'oklik.flb.jkcash.com.betaApk',
    'com.yigomob.philippine.pesogo',
    'org.loanglobally.pocketloan',
    'com.softcash',
    'com.stashfin.android',
    'bororrenkip.loan',

}


# need_add_name = name_set - loan_app_name_set
# need_add_package = package_set - loan_app_set
#
#
# print(need_add_name)
# print(len(need_add_name))
#
# print('=' * 30)
#
# print(need_add_package)
# print(len(need_add_package))


print('=' * 30)
for lan in loan_app_name_set:
    print(lan)


print('=' * 30)

for la in loan_app_set:
    print(la)




